// Copyright 2015 CloudAwan LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package deploybluegreen

import (
	"github.com/astaxie/beego"
	"github.com/cloudawan/cloudone_gui/controllers/identity"
	"github.com/cloudawan/cloudone_gui/controllers/utility/configuration"
	"github.com/cloudawan/cloudone_gui/controllers/utility/guimessagedisplay"
	"github.com/cloudawan/cloudone_utility/restclient"
	"strconv"
)

type SelectController struct {
	beego.Controller
}

func (c *SelectController) Get() {
	c.TplName = "deploy/deploybluegreen/select.html"
	guimessage := guimessagedisplay.GetGUIMessage(c)

	// Authorization for web page display
	c.Data["layoutMenu"] = c.GetSession("layoutMenu")

	imageInformation := c.GetString("imageInformation")
	currentEnvironment := c.GetString("currentEnvironment")
	autoGeneratedNodePort := c.GetString("autoGeneratedNodePort")
	nodePort := c.GetString("nodePort")
	description := c.GetString("description")
	action := c.GetString("action")

	if autoGeneratedNodePort == "on" {
		nodePort = "0"
	}

	cloudoneProtocol := beego.AppConfig.String("cloudoneProtocol")
	cloudoneHost := beego.AppConfig.String("cloudoneHost")
	cloudonePort := beego.AppConfig.String("cloudonePort")
	kubeapiHost, kubeapiPort, err := configuration.GetAvailableKubeapiHostAndPort()
	if err != nil {
		// Error
		guimessage.AddDanger("Fail to get deployable namespace")
		guimessage.RedirectMessage(c)

		// Redirect to list
		if action == "create" {
			c.Ctx.Redirect(302, "/gui/repository/imageinformation/list")
		} else {
			c.Ctx.Redirect(302, "/gui/deploy/deploybluegreen/list")
		}

		return
	}

	if action == "create" {
		c.Data["actionButtonValue"] = "Create"
		c.Data["pageHeader"] = "Create Blue Green Deployment"
		c.Data["imageInformation"] = imageInformation
		c.Data["buttonUrlCancel"] = "/gui/repository/imageinformation/list"
	} else {
		c.Data["actionButtonValue"] = "Update"
		c.Data["pageHeader"] = "Update Blue Green Deployment"
		c.Data["imageInformation"] = imageInformation
		c.Data["buttonUrlCancel"] = "/gui/deploy/deploybluegreen/list"
	}

	url := cloudoneProtocol + "://" + cloudoneHost + ":" + cloudonePort +
		"/api/v1/deploybluegreens/deployable/" + imageInformation + "?kubeapihost=" + kubeapiHost + "&kubeapiport=" + strconv.Itoa(kubeapiPort)

	namespaceSlice := make([]string, 0)

	tokenHeaderMap, _ := c.GetSession("tokenHeaderMap").(map[string]string)

	_, err = restclient.RequestGetWithStructure(url, &namespaceSlice, tokenHeaderMap)

	if identity.IsTokenInvalidAndRedirect(c, c.Ctx, err) {
		return
	}

	if err != nil {
		guimessage.AddDanger("Fail to get deployable namespace")

		// Redirect to list
		if action == "create" {
			c.Ctx.Redirect(302, "/gui/repository/imageinformation/list")
		} else {
			c.Ctx.Redirect(302, "/gui/deploy/deploybluegreen/list")
		}

		guimessage.RedirectMessage(c)
	} else {
		if len(namespaceSlice) == 0 {
			guimessage.AddDanger("No deployed application is detected so there is no namespace to select for blue green deployment")

			// Redirect to list
			if action == "create" {
				c.Ctx.Redirect(302, "/gui/repository/imageinformation/list")
			} else {
				c.Ctx.Redirect(302, "/gui/deploy/deploybluegreen/list")
			}

			guimessage.RedirectMessage(c)
		} else {
			c.Data["namespaceSlice"] = namespaceSlice
			c.Data["currentEnvironment"] = currentEnvironment
			c.Data["nodePort"] = nodePort
			c.Data["description"] = description
			if nodePort == "0" {
				c.Data["nodePort"] = ""
				c.Data["checkTagAutoGeneratedNodePort"] = "checked"
				c.Data["hiddenTagNodePort"] = "hidden"
			} else {
				c.Data["nodePort"] = nodePort
				c.Data["checkTagAutoGeneratedNodePort"] = ""
				c.Data["hiddenTagNodePort"] = ""
			}

			guimessage.OutputMessage(c.Data)
		}
	}
}

func (c *SelectController) Post() {
	guimessage := guimessagedisplay.GetGUIMessage(c)

	cloudoneProtocol := beego.AppConfig.String("cloudoneProtocol")
	cloudoneHost := beego.AppConfig.String("cloudoneHost")
	cloudonePort := beego.AppConfig.String("cloudonePort")
	kubeapiHost, kubeapiPort, err := configuration.GetAvailableKubeapiHostAndPort()
	if err != nil {
		// Error
		guimessage.AddDanger(err.Error())
		guimessage.RedirectMessage(c)
		c.Ctx.Redirect(302, "/gui/deploy/deploybluegreen/list")
		return
	}

	imageInformation := c.GetString("imageInformation")
	namespace := c.GetString("namespace")
	nodePort, _ := c.GetInt("nodePort")
	description := c.GetString("description")
	sessionAffinity := c.GetString("sessionAffinity")

	deployBlueGreen := DeployBlueGreen{
		imageInformation,
		namespace,
		nodePort,
		description,
		sessionAffinity,
		"",
		"",
		"",
	}

	url := cloudoneProtocol + "://" + cloudoneHost + ":" + cloudonePort +
		"/api/v1/deploybluegreens/" + "?kubeapihost=" + kubeapiHost + "&kubeapiport=" + strconv.Itoa(kubeapiPort)

	tokenHeaderMap, _ := c.GetSession("tokenHeaderMap").(map[string]string)

	_, err = restclient.RequestPutWithStructure(url, deployBlueGreen, nil, tokenHeaderMap)

	if identity.IsTokenInvalidAndRedirect(c, c.Ctx, err) {
		return
	}

	if err != nil {
		// Error
		guimessage.AddDanger(err.Error())
	} else {
		guimessage.AddSuccess("Create blue green deployment " + imageInformation + " success")
	}

	c.Ctx.Redirect(302, "/gui/deploy/deploybluegreen/list")

	guimessage.RedirectMessage(c)
}
